using System;
using System.Collections.Generic;
using System.Text;
using Library.Chandam.Rare;
using Library.Chandam;
using Library.Chandam.Jati;
using Library.Chandam.Jati.Akkara;
using Library.Chandam.Jati.Dvipada;
using Library.Chandam.UpaJati;
using Library.Chandam.UpaJati.Seesamu;
using Library.Chandam.Vruttam;

namespace MiriyamLib.Chandam
{

	public class Helper2
	{
		public static Rule[] GetRules2 (PadyamSubType C)
		{
			switch ( C )
			{
				case PadyamSubType.OtherUpaJati:
					return new Rule[] { new aaTaveladi ( ) , new taeTageeti ( ) , };
				case PadyamSubType.Sisamu:
					return new Rule[] { new sarvalaghusIsamu ( ) , new sarvalaghusIsamu2 ( ) , new seesaM ( ) , new seesaM2 ( ) , };

				case PadyamSubType.OtherJati:
					return new Rule[] { new utsaahamu ( ) , new kandam ( ) , new taruvOja ( ) , new tripadi ( ) };
				case PadyamSubType.Akkara:
					return new Rule[] { new aMtaraakkara ( ) , new alpaakkara ( ) , new madhuraakkara ( ) , new madhyaakkara ( ) , new mahaaakkara ( ) , };
				case PadyamSubType.Divpada:
					return new Rule[] { new dvipada ( ) , new dvipadamaalika ( ) , new maMjareedvipada ( ) };

				case PadyamSubType.RareVruttam:
					return new Rule[] { 
										new kshama(),
										new khacharaplutamu(),
										new geetaalaMbanamu(),
										new gOvRsha(),
										new gauri(),
										new chaMchareekaatati(),
										new chaMchareekaavaLi(),
										new chaMdrakaLa(),
										new chaMdralaekha(),
										new chaMdraSree(),
										new chaMdrika(),
										new chaMdrika2(),
										new chitrapadamu(),
										new jalaMdharamu(),
										new jaladamu(),
										new jaladharamaala(),
										new jalOddhatagati(),
										new tanumadhyaavRttamu(),
										new taraLamu(),
										new turagavalgitavRttamu(),
										new tvaritapadagati(),
										new dRtavilaMbitamu(),
										new dhRvakOkila(),
										new nadi(),
										new nadeepraghOshamu(),
										new narkuTamu(),
										new navanaMdini(),
										new naaMdeemukhi(),
										new naaree(),
										new naareeplutavRttamu(),
										new paadapamu(),
										new padmakamu(),
										new padmanaabhamu(),
										new paalaaSadaLamu(),
										new pRthiveevRttamu(),
										new praguNa(),
										new praNavamu(),
										new prabhaatamu(),
										new pramaaNi(),
										new pramitaaksharamu(),
										new praharaNakalita(),
										new praharshiNi(),
										new priyaMvada(),
										new priyakaaMta(),
										new phalasadanamu(),
										new baMdhuramu(),
										new balabhinmaNi(),
										new bhaMbharagaanamu(),
										new bhadrakamu(),
										new bhadrakamu2(),
										new bhadriNeevRttamu(),
										new bhaaskaravilasitamu(),
										new bhujaMgavijRMbhitamu(),
										new bhujagaSiSirutamu(),
										new bhootilakamu(),
										new bhoonutamu(),
										new maMgaLamahaaSree(),
										new maMjubhaashiNi(),
										new maMdaakraaMta(),
										new maNikamalavilasitamu(),
										new maNigaNanikaramu(),
										new maNibhooshaNamu(),
										new maNimaala(),
										new maNiraMgamu(),
										new matta(), 
										new mattamayooramu(),
										new mattahaMsini(),
										new madanavilasitamu(),
										new madanamu(),
										new madanaarta(),
										new manOj_namu(),
										new mayoorasaari(),
										new malayajamu(),
										new maeghavisphoorjitamu(),
										new maedini(),
										new vaaraaMgi(),
										new mOhapralaapamu(),
										new rati(),
										new ratipriyavRttamu(),
										new rathOddhatamu(),
										new ramaNakamu(),
										new raajahaMsa(),
										new rugmavati(),
										new ruchiramu(),
										new lata(),
										new layahaari(),
										new laaTeeviTamu(),
										new vaMSasthamu(),
										new vanamaMjari(),
										new vasaMtamaMjari(),
										new vaatOrmi(),
										new vaasaMti(),
										new vichitramu(),
										new vidyunmaala(),
										new vidrumalata(),
										new vibhootivRttamu(),
										new viSvadaevi(),
										new SarabhakreeDaa(),
										new Saalini(),
										new SikhariNi(),
										new SuddhaviraaTi(),
										new Syaeni(),
										new Sree(),
										new stree(),
										new SreeramaNamu(),
										new samaani(),
										new sarasaaMkavRttamu(),
										new sarasijamu(),
										new saadhveevRttamu(),
										new siMdhuravRttamu(),
										new siMharaekha(),
										new sukaaMti(),
										new suMdari(),
										new paMkti(),
										new sugaMdhi(),
										new tribhaMgi(),
										new vinayaM(),
										new biMbamu(),
										new aMbuja(),
										new madhumati(),
										new madaraekha(),
										new halamukhi(),
										new upajaati(),
										new iMdravaMSamu(),
										new aparaajitamu(),
										new asaMbaadha(),
										new kamalavilasitamu(),
										new sukaesaramu(),
										new hariNi(),
										new kusumitalataavaellita(),
										new aMburuhamu(),
										new aSvalalitamu(),
										new ashTamoorti(),
										new manOharamu(),
										new aMgajaastramu(),
										new varaaMgi(),
										new rathagamanamanOharamu(),
										new veeNaarachanamu()
										};

				case PadyamSubType.OtherVruttam:
					return new Rule[]{new iMdravajramu(),
										new utpalamaala(),
										new upEMdravajramu(),
										new kaviraajaviraajitamu(),
										new krauMchapadaM(),
										new chaMpakamaala(),
										new taralamu(),
										new tOTakamu(),new tOvakamu(),
										new daMDakamu1(),
										new daMDakamu2(),
										new paMchaamaramu(),
										new bhujaMgaprayaatamu(),
										new bhootilakaM(),
										new maMgaLamahaaSrI(),
										new maMdaakraaMtamu(),
										new mattakOkilamu(),
										new maththEbhaM(),
										new mahaasragdhara(),
										new maanini(),
										new maalini(),
										new mEghavisphooritaM(),
										new layagraahi(),
										new layavibhaati(),
										new vanamayooramu(),
										new vasaMtatilakamu(),
										new saardhoolaM(),
										new SlOkamu(),
										new sragdhara(),
										new sragviNi(),
										new svaagatavRttamu(),};
				default:
					return new Rule[] { };
			}
		}
		public static Rule[] GetRules (PadyamType C , bool includeRare)
		{
			switch ( C )
			{
				case PadyamType.Jati:
					return new Rule[] { new aMtaraakkara(),
										new alpaakkara(),
										new utsaahamu(),
										new kandam(),
										new taruvOja(),
										new tripadi(),
										new dvipada(),
										new dvipadamaalika(),
										new maMjareedvipada(),
										new madhuraakkara(),
										new madhyaakkara(),
										new mahaaakkara(),
										};
				case PadyamType.UpaJati:
					return new Rule[] { new aaTaveladi(),new taeTageeti(),
										new sarvalaghusIsamu(),new sarvalaghusIsamu2(),new seesaM() , new seesaM2()};
				case PadyamType.Vruttam:
					if ( !includeRare )
					{
						return new Rule[]{new iMdravajramu(),
										new utpalamaala(),
										new upEMdravajramu(),
										new kaviraajaviraajitamu(),
										new krauMchapadaM(),
										new chaMpakamaala(),
										new taralamu(),
										new tOTakamu(),new tOvakamu(),
										new daMDakamu1(),
										new daMDakamu2(),
										new paMchaamaramu(),
										new bhujaMgaprayaatamu(),
										new bhootilakaM(),
										new maMgaLamahaaSrI(),
										new maMdaakraaMtamu(),
										new mattakOkilamu(),
										new maththEbhaM(),
										new mahaasragdhara(),
										new maanini(),
										new maalini(),
										new mEghavisphooritaM(),
										new layagraahi(),
										new layavibhaati(),
										new vanamayooramu(),
										new vasaMtatilakamu(),
										new saardhoolaM(),
										new SlOkamu(),
										new sragdhara(),
										new sragviNi(),
										new svaagatavRttamu(),};
					}
					else
					{

						return new Rule[]{
										new iMdravajramu(),
										new utpalamaala(),
										new ratipriyavRttamu(),
										new upEMdravajramu(),
										new kaviraajaviraajitamu(),
										new krauMchapadaM(),
										new kshama(),
										new khacharaplutamu(),
										new geetaalaMbanamu(),
										new gOvRsha(),
										new gauri(),
										new chaMchareekaatati(),
										new chaMchareekaavaLi(),
										new chaMdrakaLa(),
										new chaMdralaekha(),
										new chaMdraSree(),
										new chaMdrika(),
										new chaMdrika2(),
										new chaMpakamaala(),
										new chitrapadamu(),
										new jalaMdharamu(),
										new jaladamu(),
										new jaladharamaala(),
										new jalOddhatagati(),
										new tanumadhyaavRttamu(),
										new taralamu(),
										new taraLamu(),
										new turagavalgitavRttamu(),
										new tOTakamu(),new tOvakamu(),
										new tvaritapadagati(),
										new daMDakamu1(),
										new daMDakamu2(),
										new dRtavilaMbitamu(),
										new dhRvakOkila(),
										new nadi(),
										new nadeepraghOshamu(),
										new narkuTamu(),
										new navanaMdini(),
										new naaMdeemukhi(),
										new naaree(),
										new naareeplutavRttamu(),
										new paMchaamaramu(),
										new padmakamu(),
										 new paadapamu(),
										new padmanaabhamu(),
										new paalaaSadaLamu(),
										new pRthiveevRttamu(),
										new praguNa(),
										new praNavamu(),
										new prabhaatamu(),
										new pramaaNi(),
										new pramitaaksharamu(),
										new praharaNakalita(),
										new praharshiNi(),
										new priyaMvada(),
										new priyakaaMta(),
										new phalasadanamu(),
										new baMdhuramu(),
										new balabhinmaNi(),
										new bhaMbharagaanamu(),
										new bhadrakamu(),
										new bhadrakamu2(),
										new bhadriNeevRttamu(),
										new bhaaskaravilasitamu(),
										new bhujaMgaprayaatamu(),
										new bhujaMgavijRMbhitamu(),
										new bhujagaSiSirutamu(),
										new bhootilakaM(),
										new bhootilakamu(),
										new bhoonutamu(),
										new maMgaLamahaaSrI(),
										new maMgaLamahaaSree(),
										new maMjubhaashiNi(),
										new maMdaakraaMta(),
										new maMdaakraaMtamu(),
										new maNikamalavilasitamu(),
										new maNigaNanikaramu(),
										new maNibhooshaNamu(),
										new maNimaala(),
										new maNiraMgamu(),
										new matta(),
										new mattamayooramu(),
										new mattakOkilamu(),
										new mattahaMsini(),
										new maththEbhaM(),
										new madanavilasitamu(),
										new madanamu(),
										new madanaarta(),
										new manOj_namu(),
										new mayoorasaari(),
										new malayajamu(),
										new mahaasragdhara(),
										new maanini(),
										new maalini(),
										new mEghavisphooritaM(),
										new maeghavisphoorjitamu(),
										new maedini(),
										new vaaraaMgi(),
										new mOhapralaapamu(),
										new rati(),
										new ratipriyavRttamu(),
										new rathOddhatamu(),
										new ramaNakamu(),
										new raajahaMsa(),
										new rugmavati(),
										new ruchiramu(),
										new lata(),
										new layagraahi(),
										new layavibhaati(),
										new layahaari(),
										new laaTeeviTamu(),
										new vaMSasthamu(),
										new vanamaMjari(),
										new vanamayooramu(),
										new vasaMtatilakamu(),
										new vasaMtamaMjari(),
										new vaatOrmi(),
										new vaasaMti(),
										new vichitramu(),
										new vidyunmaala(),
										new vidrumalata(),
										new vibhootivRttamu(),
										new viSvadaevi(),
										new SarabhakreeDaa(),
										new saardhoolaM(),
										new Saalini(),
										new SikhariNi(),
										new SuddhaviraaTi(),
										new Syaeni(),
										new sukaaMti(),
										new SreeramaNamu(),
										new SlOkamu(),
										new samaani(),
										new sarasaaMkavRttamu(),
										new sarasijamu(),
										new saadhveevRttamu(),
										new siMdhuravRttamu(),
										new siMharaekha(),
										new suMdari(),
										new paMkti(),
										new sugaMdhi(),
										new Sree(),
										new stree(),
										new sragdhara(),
										new sragviNi(),
										new svaagatavRttamu(),
										new tribhaMgi(),
										new vinayaM(),
										new biMbamu(),
										new aMbuja(),
										new madhumati(),
										new madaraekha(),
										new halamukhi(),
										new upajaati(),
										new iMdravaMSamu(),
										new aparaajitamu(),
										new asaMbaadha(),
										new kamalavilasitamu(),
										new sukaesaramu(),
										new hariNi(),
										new kusumitalataavaellita(),
										new aMburuhamu(),
										new aSvalalitamu(),
										new ashTamoorti(),
										new manOharamu(),
										new aMgajaastramu(),
										new varaaMgi(),
										new rathagamanamanOharamu(),
										new veeNaarachanamu()


										};
					}

				default:
					return new Rule[] { };
			}
			;
		}
		public static Rule[] GetAllRules (bool includeRare)
		{

			if ( !includeRare )
			{
				return new Rule[]{
															new aaTaveladi ( ) , new taeTageeti ( ) ,
										new sarvalaghusIsamu ( ) , new sarvalaghusIsamu2(),new seesaM ( )  ,  new seesaM2(),
										new utsaahamu(),new kandam(),new taruvOja(),new tripadi() ,
										new aMtaraakkara(),new alpaakkara(),new madhuraakkara(),new madhyaakkara(),new mahaaakkara(),
										new dvipada(), new dvipadamaalika(),new maMjareedvipada() ,
										new iMdravajramu(),
										new utpalamaala(),
										new upEMdravajramu(),
										new kaviraajaviraajitamu(),
										new krauMchapadaM(),
										new chaMpakamaala(),
										new taralamu(),
										new tOTakamu(),new tOvakamu(),
										new daMDakamu1(),
										new daMDakamu2(),
										new paMchaamaramu(),
										new bhujaMgaprayaatamu(),
										new bhootilakaM(),
										new maMgaLamahaaSrI(),
										new maMdaakraaMtamu(),
										new mattakOkilamu(),
										new maththEbhaM(),
										new mahaasragdhara(),
										new maanini(),
										new maalini(),
										new mEghavisphooritaM(),
										new layagraahi(),
										new layavibhaati(),
										new vanamayooramu(),
										new vasaMtatilakamu(),
										new saardhoolaM(),
										new SlOkamu(),
										new sragdhara(),
										new sragviNi(),
										new svaagatavRttamu(),
										
								};
			}
			else
			{
				return new Rule[]{
										new aaTaveladi ( ) , new taeTageeti ( ) ,
										new sarvalaghusIsamu ( ) ,new sarvalaghusIsamu2 ( ) , new seesaM ( ) ,  new seesaM2(),
										new utsaahamu(),new kandam(),new taruvOja(),new tripadi() ,
										new aMtaraakkara(),new alpaakkara(),new madhuraakkara(),new madhyaakkara(),new mahaaakkara(),
										new dvipada(), new dvipadamaalika(),new maMjareedvipada() ,
										new iMdravajramu(),
										new utpalamaala(),
										new upEMdravajramu(),
										new kaviraajaviraajitamu(),
										new krauMchapadaM(),
										new chaMpakamaala(),
										new taralamu(),
										new tOTakamu(),new tOvakamu(),
										new daMDakamu1(),
										new daMDakamu2(),
										new paMchaamaramu(),
										new bhujaMgaprayaatamu(),
										new bhootilakaM(),
										new maMgaLamahaaSrI(),
										new maMdaakraaMtamu(),
										new mattakOkilamu(),
										new maththEbhaM(),
										new mahaasragdhara(),
										new maanini(),
										new maalini(),
										new mEghavisphooritaM(),
										new layagraahi(),
										new layavibhaati(),
										new vanamayooramu(),
										new vasaMtatilakamu(),
										new saardhoolaM(),
										new SlOkamu(),
										new sragdhara(),
										new sragviNi(),
										new svaagatavRttamu(),
										new kshama(),
										new khacharaplutamu(),
										new geetaalaMbanamu(),
										new gOvRsha(),
										new gauri(),
										new chaMchareekaatati(),
										new chaMchareekaavaLi(),
										new chaMdrakaLa(),
										new chaMdralaekha(),
										new chaMdraSree(),
										new chaMdrika(),
										new chaMdrika2(),
										new chitrapadamu(),
										new jalaMdharamu(),
										new jaladamu(),
										new jaladharamaala(),
										new jalOddhatagati(),
										new tanumadhyaavRttamu(),
										new taraLamu(),
										new turagavalgitavRttamu(),
										new tvaritapadagati(),
										new dRtavilaMbitamu(),
										new dhRvakOkila(),
										new nadi(),
										new nadeepraghOshamu(),
										new narkuTamu(),
										new navanaMdini(),
										new naaMdeemukhi(),
										new naaree(),
										new naareeplutavRttamu(),
										new paadapamu(),
										new padmakamu(),
										new padmanaabhamu(),
										new paalaaSadaLamu(),
										new pRthiveevRttamu(),
										new praguNa(),
										new praNavamu(),
										new prabhaatamu(),
										new pramaaNi(),
										new pramitaaksharamu(),
										new praharaNakalita(),
										new praharshiNi(),
										new priyaMvada(),
										new priyakaaMta(),
										new phalasadanamu(),
										new baMdhuramu(),
										new balabhinmaNi(),
										new bhaMbharagaanamu(),
										new bhadrakamu(),
										new bhadrakamu2(),
										new bhadriNeevRttamu(),
										new bhaaskaravilasitamu(),
										new bhujaMgavijRMbhitamu(),
										new bhujagaSiSirutamu(),
										new bhootilakamu(),
										new bhoonutamu(),
										new maMgaLamahaaSree(),
										new maMjubhaashiNi(),
										new maMdaakraaMta(),
										new maNikamalavilasitamu(),
										new maNigaNanikaramu(),
										new maNibhooshaNamu(),
										new maNimaala(),
										new maNiraMgamu(),
										new matta(),
										new mattamayooramu(),
										new mattahaMsini(),
										new madanavilasitamu(),
										new madanamu(),
										new madanaarta(),
										new manOj_namu(),
										new mayoorasaari(),
										new malayajamu(),
										new maeghavisphoorjitamu(),
										new maedini(),
										new vaaraaMgi(),
										new mOhapralaapamu(),
										new rati(),
										new ratipriyavRttamu(),
										new rathOddhatamu(),
										new ramaNakamu(),
										new raajahaMsa(),
										new rugmavati(),
										new ruchiramu(),
										new lata(),
										new layahaari(),
										new laaTeeviTamu(),
										new vaMSasthamu(),
										new vanamaMjari(),
										new vasaMtamaMjari(),
										new vaatOrmi(),
										new vaasaMti(),
										new vichitramu(),
										new vidyunmaala(),
										new vidrumalata(),
										new vibhootivRttamu(),
										new viSvadaevi(),
										new SarabhakreeDaa(),
										new Saalini(),
										new SikhariNi(),
										new SuddhaviraaTi(),
										new Syaeni(),
										new Sree(),
										new stree(),
										new SreeramaNamu(),
										new samaani(),
										new sarasaaMkavRttamu(),
										new sarasijamu(),
										new saadhveevRttamu(),
										new siMdhuravRttamu(),
										new siMharaekha(),
										new sukaaMti(),
										new suMdari(),
										new paMkti(),
										new sugaMdhi(),
										new matta(),
										new tribhaMgi(),
										new vinayaM(),
										new biMbamu(),
										new aMbuja(),
										new madhumati(),
										new madaraekha(),
										new halamukhi(),
										new upajaati(),
										new iMdravaMSamu(),
										new aparaajitamu(),
										new asaMbaadha(),
										new kamalavilasitamu(),
										new sukaesaramu(),
										new hariNi(),
										new kusumitalataavaellita(),
										new aMburuhamu(),
										new aSvalalitamu(),
										new ashTamoorti(),
										new manOharamu(),
										new aMgajaastramu(),
										new varaaMgi(),
										new rathagamanamanOharamu(),
										new veeNaarachanamu()


						};
			}
		}
	}
}
